### ISSUE TITLE
Getactor panics when checking for inactive instances on startup

### ISSUE THREAD

**Issue by knotteye** [FChannel0/FChannel-Server#58]
Full stacktrace below, this happens immediately after I start my server while Fchannel is looking for inactive instances. The error is from the http.NewRequest call in GetActor (main.go: 1877).

```
Oct 03 07:37:29 nyx Server[2057473]: error with getting actor req
Oct 03 07:37:29 nyx Server[2057473]: panic: parse " https://chan.clubcyberia.co/out": first path segment in URL cannot contain colon
Oct 03 07:37:29 nyx Server[2057473]: goroutine 38 [running]:
Oct 03 07:37:29 nyx Server[2057473]: main.CheckError(0x980da0, 0xc00036ede0, 0x8f0d5e, 0x1c, 0xc000216340, 0x20)
Oct 03 07:37:29 nyx Server[2057473]:         /var/lib/fitchan/FChannel-Server/main.go:1458 +0x135
Oct 03 07:37:29 nyx Server[2057473]: main.GetActor(0xc000216340, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Oct 03 07:37:29 nyx Server[2057473]:         /var/lib/fitchan/FChannel-Server/main.go:1877 +0x385
Oct 03 07:37:29 nyx Server[2057473]: main.CheckInactiveInstances(0xc00009dc70, 0x0)
Oct 03 07:37:29 nyx Server[2057473]:         /var/lib/fitchan/FChannel-Server/main.go:2993 +0x4b8
Oct 03 07:37:29 nyx Server[2057473]: main.CheckInactive(0xc00009dc70)
Oct 03 07:37:29 nyx Server[2057473]:         /var/lib/fitchan/FChannel-Server/main.go:2960 +0x2b
Oct 03 07:37:29 nyx Server[2057473]: created by main.main
Oct 03 07:37:29 nyx Server[2057473]:         /var/lib/fitchan/FChannel-Server/main.go:79 +0x18e
```

**Comment by FChannel0** [comment]
very interesting. i will look more into this, thank you for reporting.

**Comment by knotteye** [comment]
Solved. This happens when there is some whitespace in the url being checked. I don't want to be modifying existing databases so I just put in a string.TrimSpace to make sure it's a valid URL before firing the request. Will send a PR.
