### ISSUE TITLE
Does not work on openbsd

### ISSUE THREAD

**Issue by Lucas32578** [FChannel0/FChannel-Server#67]
running the program returns the following:

```
Successfully connected DB

error with create trip code


panic: exec: "sha512sum": executable file not found in $PATH

goroutine 1 [running]:
main.CheckError({0x4e2ae0, 0x4000188040}, {0x44f637, 0x1b})
	/var/www/FChannel-Server/main.go:1458 +0x110
main.CreateTripCode({0x4000192120, 0x20})
	/var/www/FChannel-Server/main.go:1513 +0x140
main.CreateKey(0x20)
	/var/www/FChannel-Server/main.go:1488 +0x3c
main.main()
	/var/www/FChannel-Server/main.go:73 +0x98
exit status 2
```

i have tried symlinking the openbsd equivalent of this command, sha512, to sha512sum, but that also dosent work:

```
Successfully connected DB
panic: runtime error: index out of range [10] with length 10

goroutine 1 [running]:
main.CreateKey(0x20)
	/var/www/FChannel-Server/main.go:1490 +0x138
main.main()
	/var/www/FChannel-Server/main.go:73 +0x98
exit status 2
```

**Comment by Lucas32578** [comment]
Going to close this issue, as I fixed it by installing the coreutils package. However, from this a new issue arose which I will explain in detail in another issue
