### ISSUE TITLE
does not run on OpenBSD #2

### ISSUE THREAD

**Issue by Lucas32578** [FChannel0/FChannel-Server#68]
running on a raspberry PI 4 with openbsd i get this error

```
Successfully connected DB
board exists
convert: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1447.

error with captcha second pass

panic: exit status 1

goroutine 18 [running]:
main.CheckError({0x4e2920, 0x4000109020}, {0x4517d7, 0x1e})
	/var/www/FChannel-Server/main.go:1458 +0x110
main.CreateNewCaptcha(0x400007f1e0)
	/var/www/FChannel-Server/verification.go:425 +0x4c8
main.MakeCaptchas(0x400007f1e0, 0x64)
	/var/www/FChannel-Server/main.go:2027 +0x50
created by main.main
	/var/www/FChannel-Server/main.go:71 +0x88
exit status 2
```

**Comment by FChannel0** [comment]
You will have to download the helvetica ttf font and place it into your fonts directory. Will most likely need to run fc-cache -rv to be safe. I will remove this need for helvetica to a free font in future releases its just the default that imagemagick seems to choose.

**Comment by Obazzi** [comment]
Every once in a while I go on some threads and I see someone mention BSD. Whenever I ask why I should use BSD over GNU/Linux, some guy in a punisher t-shirt starts to lecture me about the philosophy of Lionel Richie, and says some non sequitur about systemd. Listen man I have a D ready for you, fucking bitch. I don't give a fuck about your liberal sociology. I just want Steam to fucking work on my computer. I want my Wi-Fi to work. I'm always told, BSD is a complete operating system, it doesn't use distros like Linux. And then I look at the fucking piles of **BSD DISTROS** online. FreeBSD, OpenBSD, NetBSD, TrueOS, DragonFly BSD. And wow, they all suck, and they're all distros.

And these are just the online BSD people. Once you get into real life, it's even worse. I go to the BSD conference, and it looks like a fucking Starbucks. It's all rich millennials and baby boomers, sitting at their fucking MacBook Pros, jacking themselves off about how they run a BSD OS on their fucking Apple shitbox. **YOU AREN'T A PRO HACKER FOR RUNNING MACOS, you fucking dipshit. Nobody cares. INSTALL GENTOO!**

Okay, okay, okay, okay. I'm at the fucking BSD conference, this guy comes up, George or some shit. It's that fucking egg man looking guy who is in every BSD shilling video, it's like it's his full-time job to tell people to run FreeBSD. He doesn't even run fucking FreeBSD because in every video I see, he's sitting at a MacBook Pro running macOS. Wow, you run your own operating system in a virtual machine only, it must be so great, right! He's always mumbling about how he made the fucking network stack for macOS. Gee, I wonder how much you got paid for that bud, oh yeah fucking nothing. Great job buddy, happy for you. At least you got Apple to give off the code they added, right? Wait, wrong, you didn't because you used a **CUCK LICENSE!** Billionaires are making money off of over 20 years of this guy's fucking work. He got nothing in return, he got no source code. And he's proud of this, incredible!

Wait a minute, do you hear that?!

**_TOO BAD YOU DIDN'T USE THE GPL KIDDO!_**

Wow, thanks Stallman! It sure does feel good to be free.

Imagine what it's like being this bald guy, working on a free OS for decades, just for it to be used to spy on users and make billionaires more money. Imagine being proud of this! BSD is a cuck operating system and running it is an embarrassment. This is why you don't run BSD.

###### Besides it being really bad on desktop, that's also a reason.
